### ISSUE TITLE
Support OpenSearch 2.x and Elasticsearch 8.x

### ISSUE THREAD

**Issue by turesheim** [rfoltyns/log4j2-elasticsearch#81] opened 2022-05-16 07:40 UTC
**Description**
OpenSearch 2.0 and Elasticsearch 8.0 har removed the option to specify types in requests and any call from log4j2-elasticsearch to mentioned instances will return something like this and fail:

`2022-05-13 08:07:36,304 [I/O dispatcher 1] DEBUG -  - http-outgoing-4 << "{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}"`

**Configuration**
I don't think we need a particular configuration to recreate this.

**Runtime (please complete the following information):**
- OpenSearch 2.0RC1 
- log4j2-elasticsearch-hc 1.5.2
 
**Additional context**
* https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html
* https://github.com/opensearch-project/OpenSearch/issues/1940

**Comment by kamuffe** [comment] 2022-10-05 17:39
Hi.

First of all thanks for this great project.
We already upgrated to ElasticSearch 8.4 and since then now logs are sent to ElasticSearch anymore due to this issue.

Can you already weigh up when you have time to fix this issue?

Best,
Kamuffe

**Comment by rfoltyns** [comment] 2022-10-05 22:00
Thank you for the good word. I'm glad that you found it useful.

I have the code working. Just wrapping up testing. I can actually push it today.

**Comment by rfoltyns** [comment] 2022-10-05 22:57
I'll try to release it later this month

**Comment by kamuffe** [comment] 2022-10-11 08:05
Thank you very much ;)

I really appreciate that :)

**Comment by kamuffe** [comment] 2022-10-13 06:33
Thank you very much ;)

I really appreciate that :)

**Comment by rfoltyns** [comment] 2022-11-07 12:40
Released in 1.6.0.

OpenSearch 2.0 support is limited to legacy Index Template API (no composable templates).

ISM is out-of-scope of this project - it will be a part of `log4j2-opensearch` project in the future. For now, you can get it by extending `OperationFactoryDispatcher` and `ClientObjectFactory` classes in a module you're using and adding appropriate `Operation` factory:
* `ElasticsearchOperationFactory` and `HCHttpPlugin` (or `HCHttp` for programmatic config) in HC module
* `ElasticsearchOperationFactory` and `AHCHttpPlugin` (or `AHCHttp` for programmatic config) in AHC module
* `JestOperationFactoryDispatcher` and `(Buffered)JestHttpObjectFactory` in Jest module

**Closed by rfoltyns** 2022-11-07 12:40 UTC

**Comment by turesheim** [comment] 2022-11-09 15:51
Thanks for adding OpenSearch 2.0 support. It is very much appreciated! PS: We _are_ using OpenSearch 2.3 with composable templates and this version of library. I'm not aware of anything broken. Could you elaborate?

**Comment by rfoltyns** [comment] 2022-11-09 18:42
@turesheim Great news! :+1: I'm glad you got it working.

I tested it only against 2.0 tbh. I had trouble with the API - I don't remember why anymore. I need to revisit it then.

I'll happily make slight adjustments and accept PR for OpenSearch. However, given that it's forked from ES 7.10, API compatibility will unfortunately be only a side-effect rather than the goal of this project. This will obviously change once `log4j2-opensearch` come to life. I only have 2 hands though...

**Comment by kamuffe** [comment] 2022-11-11 07:33
Hi.

Thank you for releasing this issue.
I can confirm, that the ES reporting with ElasticSearch 8.4.3 is working again.

Best,
Kamuffe
