### ISSUE TITLE
Exception in thread "BatchNotifier" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by paskalka** [rfoltyns/log4j2-elasticsearch#25] opened 2019-08-30 06:11 UTC
Hello,

I am getting :+1: 
2019-08-30 09:06:54,998 BatchNotifier ERROR Deferred operation failed: IndexTemplate not added: {"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{strings={mapping={type=keyword}, match_mapping_type=string, match=*}}], _all={enabled=false}, properties={loggerName={type=text, fields={keyword={ignore_above=256, type=keyword}}}, message={type=text, fields={keyword={ignore_above=256, type=keyword}}}, timeMillis={format=epoch_millis, type=date}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{strings={mapping={type=keyword}, match_mapping_type=string, match=*}}], _all={enabled=false}, properties={loggerName={type=text, fields={keyword={ignore_above=256, type=keyword}}}, message={type=text, fields={keyword={ignore_above=256, type=keyword}}}, timeMillis={format=epoch_millis, type=date}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{strings={mapping={type=keyword}, match_mapping_type=string, match=*}}], _all={enabled=false}, properties={loggerName={type=text, fields={keyword={ignore_above=256, type=keyword}}}, message={type=text, fields={keyword={ignore_above=256, type=keyword}}}, timeMillis={format=epoch_millis, type=date}}}]"}}

Exception in thread "BatchNotifier" java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.google.gson.Gson.getAdapter(Gson.java:434)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)

Thanks for your help

**Comment by rfoltyns** [comment] 2019-08-30 11:42
@paskalka you have to use a mapping definition that's compatible with your current version of ES cluster.
Have a look at indexTemplate-x.json files [here](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-jest/src/test/resources) for some very basic test examples. They won't give you a lot of search capabilities, but at least you'll get the basic JSON structure required by each ES version.

**Comment by rfoltyns** [comment] 2019-09-27 19:14
@paskalka Are you still having this issue? I've reproduced the template parsing error by providing indexTemplate-6.json to ES 7 cluster (as expected).

I couldn't reproduce the `StackOverflowError` though. Could you provide me with more information or steps to reproduce?

Since there were GSON classes in the stacktrace, I'd recommend to configure object pooling as it uses a Jackson serializers and it's much more memory efficient - Jest classes based on GSON serialization allocate huge amounts of memory.

**Comment by rfoltyns** [comment] 2019-11-15 22:37
I've managed to reproduce a `StackOverflowError`. @paskalka are you still getting it after [this change](https://github.com/rfoltyns/log4j2-elasticsearch/commit/74f8e72e921ae70649092d0d3947d4f19cc30b3c)?

**Comment by rfoltyns** [comment] 2020-03-28 01:29
`StackOverflowError` was thrown from GSON trying to serialize pooled ByteBuf. It's possible only when non-pooled `jest` config (`JestHttp`) was configured with pooled `JacksonJsonLayout`. This configuration is invalid and it's documented in `core` module.

Fixed in 1.3.6. - `ConfigurationException` is thrown earlier to indicate invalid usage in runtime.

**Closed by rfoltyns** 2020-03-28 01:29 UTC
