### ISSUE TITLE
Testing with Elasticsearch7.x

### ISSUE THREAD

**Issue by rajeshwaranmsc** [rfoltyns/log4j2-elasticsearch#22] opened 2019-07-20 06:51 UTC
Hi,

I am just starting to use this library. From your documentation it mentioned it works up till elastic search 6.x. I tested against elasticsearch 7.2, I can see the logs via Kibana, except the date that is millisecond. I tried possible option like 
1. creating the index in elastic search rather than from code. 

But no luck. Any insight would help to greater extend.

regards
Raj

**Comment by rfoltyns** [comment] 2019-07-22 00:16
Date in millisecond is caused by lack of mappings for `timeMillis` field. There was a breaking change in mappings in 7.0 and I may need to update the code to conform to that. I'll keep you posted.

**Comment by rfoltyns** [comment] 2019-08-12 08:47
1.3.5 was released over the weekend. Could you retest with the `mappingType` config below? 
```
<JestHttp serverUris="${esHosts}" mappingType="_doc"/>
```
(will work for both `JestHttp` and `JestBufferedHttp`)

Also, make sure that `IndexTemplate` is created corrrectly during the startup if you're using it. This will prevent issues related with `timeMillis`.

**Comment by Marx2** [comment] 2020-01-15 07:48
You can also use:
<KeyValuePair key="@timestamp" value="${date:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"/>
It's correctly discovered by ES as date type

**Comment by rfoltyns** [comment] 2020-05-22 17:48
Configurable `mappingType` released in 1.3.5

**Closed by rfoltyns** 2020-05-22 17:48 UTC
Labels: howto
